### ISSUE TITLE
Enable ppc64le support

### ISSUE THREAD

**Issue by seth-priya** [ManageIQ/container-postgresql#18]
Needed for infrastructure management

The base image used in the Dockerfile centos/postgresql-10-centos7 is not multi-arch and seems to be built from https://github.com/sclorg/postgresql-container/blob/generated/10/Dockerfile which again relies on centos/s2i-core-centos7 which is not multi-arch either.

Looking at alternatives to get this working

**Comment by seth-priya** [comment]
I could build the centos/s2i-core-centos7 image for ppc64le , however the build for postgresql-container based on that fails

No package rh-postgresql10 available.
No package rh-postgresql10-syspaths available.
No package rh-postgresql96-postgresql-server available.

…..


Error: Package: rh-postgresql10-postgresql-libs-10.12-2.el7.ppc64le (centos-sclo-rh)
Requires: rh-postgresql10-runtime
Error: Package: rh-postgresql10-postgresql-10.12-2.el7.ppc64le (centos-sclo-rh)
Requires: rh-postgresql10-runtime
Error: Package: rh-postgresql10-postgresql-contrib-10.12-2.el7.ppc64le (centos-sclo-rh)
Requires: rh-postgresql10-runtime

I land up in a similar situation when using the uib7/s2i-core image from RHCC and trying to build postgresql-container on top of it as rh-postgresql* packages are still coming from the Centos SCL repos.

Since, the postgresql10 binaries are installed from the centos repos inside ubi8.2 container at other points in the manageiq build process, using the same combination to try and create a PostgreSQL10 image ..

**Comment by seth-priya** [comment]
Question - can we consider using 
https://hub.docker.com/_/postgres (alpine based, official image), https://github.com/docker-library/postgres/blob/master/10/Dockerfile

**Comment by seth-priya** [comment]
@carbonin

**Comment by carbonin** [comment]
I don't think there's any reason we couldn't, but I don't think it would be trivial as we rely on some hooks to create our superuser currently that may not be in every image.

Assigning to @bdunne as I'm not actively working on this project anymore.

**Comment by bdunne** [comment]
cc @simaishi

**Comment by seth-priya** [comment]
@carbonin @bdunne slightly unrelated question, I am trying to get a code contribution approval for this repository and wanted to confirm that this is under Apache 2.0 as well like the other ManageIQ components? Could you please confirm? thank you!

cc @gerrith3

**Comment by Fryguy** [comment]
Another possiblity - https://catalog.redhat.com/software/containers/rhel8/postgresql-10/5ba0ae0ddd19c70b45cbf4cd

**Comment by Fryguy** [comment]
@seth-priya Yes, it should be Apache 2.0.  I'm surprised we don't have a license nor readme here.  If you can make a PR it would be appreciated.

**Comment by seth-priya** [comment]
@Fryguy thanks for confirming, I have raised the PR.

**Comment by seth-priya** [comment]
For the image itself, I had tried and was able to build https://github.com/sclorg/s2i-base-container.git with build TARGET=centos7 for ppc64le without any changes and further using that built image as the base I was able to build https://github.com/sclorg/postgresql-container as well with these changes

````
diff --git a/10/Dockerfile b/10/Dockerfile
index a0fee51..0e9f0cb 100644
--- a/10/Dockerfile
+++ b/10/Dockerfile
@@ -42,7 +42,10 @@ COPY root/usr/libexec/fix-permissions /usr/libexec/fix-permissions
 # safe in the future. This should *never* change, the last test is there
 # to make sure of that.
 RUN yum install -y centos-release-scl-rh && \
-    INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper rh-postgresql10 rh-postgresql10-postgresql-contrib rh-postgresql10-syspaths rh-postgresql96-postgresql-server" && \
+    yum install -y https://cbs.centos.org/kojifiles/packages/rh-postgresql10/3.1/1.bs1.el7/ppc64le/rh-postgresql10-runtime-3.1-1.bs1.el7.ppc64le.rpm \
+                   https://cbs.centos.org/kojifiles/packages/rh-postgresql10/3.1/1.bs1.el7/ppc64le/rh-postgresql10-3.1-1.bs1.el7.ppc64le.rpm \
+                   https://cbs.centos.org/kojifiles/packages/rh-postgresql10/3.1/1.bs1.el7/ppc64le/rh-postgresql10-syspaths-3.1-1.bs1.el7.ppc64le.rpm && \
+    INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper rh-postgresql10-postgresql-contrib" && \
     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS && \
     rpm -V $INSTALL_PKGS && \
     yum -y clean all --enablerepo='*' && \
````
and container-postgresql subsequently builds and works fine (tested in standalone mode as well as as part of manageiq OCP deployment).

However, I am not sure if the location from which I have picked up the ppc64le RPMS above is ideal but I have not been able to find alternatives yet, I will try to search again .. 

But the other challenge would be to make these upstream images for Power available so that they can be pulled directly, right now I have to build two levels before I can get to this one.

Thanks for your suggestion on using the RHCC image as well.. we are trying that and will post our findings soon, however, at this point it does not look like it will work as is, changes will be needed ..

**Comment by junawaneshivani** [comment]
I tried using https://catalog.redhat.com/software/containers/rhel8/postgresql-10/5ba0ae0ddd19c70b45cbf4cd image as base to build https://github.com/sclorg/postgresql-container with TARGET=rhel7 and VERSIONS=10, but the build failed with below error. 
```
2020-08-20 09:18:54,110 [ERROR] yum:34:MainThread @logutil.py:194 - [Errno 13] Permission denied: '/var/log/rhsm/rhsm.log' - Further logging output will be written to stderr
Not root, Subscription Management repositories not updated
Error: This command has to be run under the root user.
```
The base container runs as postgres user not allowing any package installation....

**Comment by seth-priya** [comment]
A few more observations,

1- It is specifically the "runtime" package that is "rh-postgresql10-runtime" which is missing, the latest and update versions of all the packages for rh-postgresql10 for ppc64le are available
https://cbs.centos.org/koji/buildinfo?buildID=29164
http://centos-altarch.reloumirrors.net/7/sclo/ppc64le/rh/Packages/r/

2- the runtime package for rh-postgresql12 "IS" available and the only thing that causes an issue in building https://github.com/sclorg/postgresql-container/tree/generated/12
is the install of "rh-postgresql10-postgresql-server" on line
https://github.com/sclorg/postgresql-container/blob/139dafa98fac426226aff22ab0da4aabbf6e188f/12/Dockerfile#L45
No other changes are needed to any of the Dockerfiles

**Comment by seth-priya** [comment]
Created an issue at https://github.com/sclorg/postgresql-container/issues/384

**Comment by seth-priya** [comment]
just a quick update - as per discussion on ^^ issue, we now have the rh-postgresql10 packages available from the official CentOS repo. for ppc64le and the base PostgreSQL images build mostly without changes on Power and I have validated the Dockerfile in this repo. as well - no changes will be required here once the base images are available externally, I am trying to get a handle on how that can be accomplished.

**Comment by bdunne** [comment]
https://github.com/ManageIQ/container-postgresql/pull/29 adds support for other architectures

**Comment by Fryguy** [comment]
ppc64 is working via #29 (confirmed downstream), so closing
