### ISSUE TITLE
Convert to UBI8

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/container-postgresql#20]
We should move forward to a ubi8 based container, also to align with the other containers.  This may unlock #18 as well.  When we switch should we switch to a vanilla postgres, or to something like the crunchydata image?

**Comment by Fryguy** [comment]
@bdunne Since we use ubi8/s2i-core, is this basically done?

**Comment by bdunne** [comment]
I think so.  It looks like s2i-core is based on UBI https://catalog.redhat.com/software/containers/ubi8/s2i-core/5c83967add19c77a15918c27?container-tabs=dockerfile
