### ISSUE TITLE
postgresql logs should go to STDOUT as well

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/container-postgresql#40]
cc @jrafanie

**Comment by Fryguy** [comment]
Particularly the slow query log, which is useful.

**Comment by jrafanie** [comment]
Additionally, we disable log rotation age

https://github.com/ManageIQ/manageiq-pods/blob/e939852d877a4a1a6903af660a118be33cfe00cf/manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql_conf.go#L42
