### ISSUE TITLE
[RFE] Do versioning

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/container-postgresql#7]
We should version this container in some sane way so that the released versions of ManageIQ can reference the correct version of the postgres packages.

**Comment by chessbyte** [comment]
@carbonin is this still a valid issue?

**Comment by carbonin** [comment]
So it seems like we have versioned tags now, but I think it would make sense to have versioned branches in this repo going forward. That way we can rebuild a particular version to get the latest packages and such.

So, yes, I think this issue is still valid.

**Comment by bdunne** [comment]
I'm going to mark this as done since we are pushing version tags to the registry now.
